oopsy:
  rails-application:
    image:
      tag: master
      pullPolicy: Always
    environment:
      sealedSecrets: true
      plain:
        PUBLIC_HOST: "oopsy.home.klaus-meyer.net"
        PUBLIC_PORT: "443"
        PUBLIC_SCHEME: "https"
        REDIS_URL: "redis://oopsy-redis:6379/0"
        WEBHOOK_DISCORD_ENABLED: "true"
        WEBHOOKS_ENABLED: "true"
      secret:
        DATABASE_URL: AgANyoX9Y02NMaQE2E703tYgTxcH8QMpEA3vJoGCjXlCr0CWMge2loMp7DZic2Y3eCZIMaj9tjABSt6nkDoE7G8w1sflFZaJTv239uUyWwVo29ZLwppTB2yb55MRsikoIziV72XuqNx7LTpbtOHsCRIUt8xYvtNYlu0o7qTtOxutwLDky2MYTiq2AOoxkNBMTXf0IkjEholysAFUTRJNnw9R7DZIFeI64V8s7Ixte9hR/GXt99o8dBqSymG+9OeIIN9oK7PtIQqT/QgtStqE0SWXD1T1oZPVWJfpTRgvTpRnjUAPMt+E3qmZzuw5mxEhq8GSwk2W1O06i9L18kH/Ie1HAk9zy70vPV8Hqw0IX+lTEsu3CEWDJ2fk8L+AfNV3cyb9D6cPaiGomv4y1bpqnijFcMxlFE5X1/oxH4XoEREDdj89G+zRown+43CLCaP+UTejLkCJjPVNflLcE5cE4/neeyrJee1T7aBtxrCt+WEiEr/5tDjs/kWrOX/QFYVAtX+ZjnnI66SiYeX6lgRgw08h1kSyyUHIwSes215uo8Nm5nJOU5uuxhno8r7UI4Io8FeU7KKM8lTHlio8Us4xORhtUshV9z1W3tbFqvquWc7E7gGBkiSHkn8/fEyjzMSmw2uTveKFw7z988ngqG5E2yfircdFKdH7Ovp9M7pr+qiNkEiArUxjC29cJzwm5fYcgXkSf3a5itS7oRKXmWUCI0oOkkB5dG0d1fEjNdur2YvO9ErLHNeY4xFoBuGoS89uKdPKl+QiWNSJKPaxpG3Dkr10/9EPeyX7mBXakRyQIBWf7d86uJhNi5xagFWa3vZapD9D
        SECRET_KEY_BASE: AgBN67JYCA3gvsz4S//wjeMLtNI1Xfu556ZiJ3NpFoyGHUNri7+abmmawmGl/6qqDTqgTz9XR0/g4TKKuH+jSXffi0hyYfYmyhi6hNZhRo8Cs31zRP8KGCWYenqK0ZVyGnn73iQNFWTVqg+ZDpsdVeoiPNtF3zEKBp++/57C9/uE68dM/xPCZKYzLndXzvHSxS+yUATKBx9w7KV6pFyM2riEryC4MGLNkqNBeJt5tzJ7whs+YD+KjUe78p/TDAfbDHTfwvMOjOyCfiZRtpE4HpHJ/1v9dcNyCaCaIrifjLf/LOii+gcmBtiA9XI7RaVa6gQ9sUE8dSNQ12qxRGM4+fqeOmvrPhKVf5i7UqOWl7IC9Mys05ZftN+TCWyc5eQzpbAwO6T/+R4e+D+DDtyFBe1LFc2z2HjvutMDxvPUsxmRvxWw6zHfi02BoiTsG0DCYBF3rkhJX/G+9esbICAekRWorvbf7+xwDm2W3xDFvsxnHGPXe+BBGCMeiAVMvaRf1PkdxrvzxHcRsXv6x/HTEouJufcjA0aC+L/PlaYuvBxDE4xlQKCuds7L7MfgX83BMum/U3TYvSM0eqzjVc4lyyhNKTkN+z6ezpL6oonkuIJGoSgu7iVmx32f9EO9mv32WoMmLlYHzVacoVHu/zhSlxTZKb70OczINbFjLf5J3LLLzJnnRk7e5kH5d/mLl2RVzJ9CBa6cdY6D8Hpvm5HUFe3/ALkYx3oPd8rOXBpKIEuCFw==
        WEBHOOK_DISCORD_URL: AgAnV+w4Wp0Oloef9WT6zoix9/Wqf7WNhHqvEmJcIMdqisT6bChissvzuJvxSAqPhWy0kW6KyF37iAM7+TdKkKnoliLf3pkAAUwLKx5ZlDUBBnKNw0iDDoV0FIGZrhLgzsXmf42gY6r417xA+lunpI7wBE6+I86eiLemRfbSVfuhAn3MRFSrPKl6eRs/Y9xUBz7csQ6amCTqQg7afC6LIJTapB7lp7RK/0ml5J8DiEgbnPeokiZJdt1r89+U/5rjiJntjw1tmjZKwe6mTjml6ALjMF+8UItUuL8VZhFmFSDHSC6C3KlUS4LDPSM+wQjUlFCtRdnx3zKgpJjkBQ/wLs0uI54vmjovNtgBCN/VI7rgoHTRf2zN2BM5nP6zTE3YNdZ+KHDj4syNBVSzFoEj3GFUwFLJ/rbvfzX3GQKxXQz3PmhoCBGf/clJ7tgrf63y62G+yggs2qTx7cyRveIUtPzCOvjzaNKy3asQxgsPQ0hfwYP2syCxl6Ur2pOTHImSUjWRSG0S7pyr8uCaUGASKjhJ8NAs8BmNxsnr8FeGPZmEhrhC68ymMucG+cx8VtfcXhUK9QiXZ8X3msincaQ4rbHf2EQ3ueevUwA5dFpIeefb6YSzNVMCdaDhxRtbUOiwD0ukTI/dMCa4oZ2vkqAJTurQSASRQpgJFWd9tHhV87cqIoDwCbnTyVRuULqMgcW11TrNalZbgPSwYkxqzde3GA/dWy9ybCjtjrekd6DARszSGtE5KyctS0icim8XO3jRTOTNawEEoH3m1ZZZ/Q1NxRWehj/JrszNdjg2/CjzGvdGI24k5S59ho6ursruFHF2LZxtk6M7WzlW2jB8Wph9n4ek0UuTzMsCdpVT
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/common-name: "*.home.klaus-meyer.net"
      hosts:
        - host: oopsy.home.klaus-meyer.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tls-wildcard-home-klaus-meyer-net
          hosts:
            - "*.home.klaus-meyer.net"
